# Формат лога (nginx combined)
time-format %T
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

# Опции вывода
real-time-html true
daemon-mode false
port 7890
addr 0.0.0.0
geoip-database /usr/share/geoip/GeoIPCity.dat  # опционально

# ignore-404 true

# Цвета и оформление
color-scheme 1
html-prefs {"theme":"dark"}